apiVersion: v1
kind: Service
metadata:
  name: contosodemo
  namespace: namespace-workflow-1732190088452
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: contosodemo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000